apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: go-demo
  template:
    metadata:
      labels:
        app: go-demo
    spec:
      containers:
      - name: go-container
        image: lijie1xia/go-project:go-hello
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080