name: Deploy Go + Nginx to K3s

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Go Docker Image
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=go-hello-${{ github.sha }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t lijie1xia/go-project:$IMAGE_TAG . 

      - name: Push Docker image
        run: |
          docker push lijie1xia/go-project:${{ env.IMAGE_TAG }}

      #  Copy yaml to Ubuntu
      - name: Upload Nginx YAML
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "nginx-go-config.yaml"
          target: "/home/${{ secrets.SSH_USER }}/"

      # Deploy to K3s via SSH
      - name: Deploy to K3s
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Deploy Go app..."
            sudo k3s kubectl set image deployment/go-deployment go-container=lijie1xia/go-project:${{ env.IMAGE_TAG }}
            sudo k3s kubectl rollout restart deployment/go-deployment
            sudo k3s kubectl rollout status deployment/go-deployment
  
            echo "Deploy Nginx..."
            sudo k3s kubectl apply -f /home/${{ secrets.SSH_USER }}/nginx-go-config.yaml
            sudo k3s kubectl rollout restart deployment/nginx-go-deployment
            sudo k3s kubectl rollout status deployment/nginx-go-deployment

